### PR TITLE
docs: added link to poetry version of the template

### PR DESCRIPTION
**Pull request by jnoortheen**
in case someone wants less files to fiddle with

### CODE REVIEW

**Comment by anki-code** [comment]
Thanks @jnoortheen ! I'm not the guru in poetry but may be the name should reflect the poetry i.e. `xontrib-cookiecutter-poetry`?

**Comment by jnoortheen** [comment]
I just forked it and updated it in a hurry. I will try renaming it.

**Comment by jnoortheen** [comment]
renamed to https://github.com/jnoortheen/xontrib-cookiecutter-poetry

**Comment by gforsyth** [comment]
Sorry for the delay, @jnoortheen, I'd missed this

**Pull request merged**
